// Realistic default restaurant state matching GloriaFood & FoodBooking
export const defaultRestaurant = {
  id: 'resto-bella-vista-001',
  name: 'Bella Vista Gourmet Kitchen & Pizzeria',
  slug: 'bellavista-pizza',
  description: 'Authentic stone-oven Neapolitan pizzas, artisan smashed burgers, fresh handmade pastas and handcrafted Italian dolci. Voted #1 Downtown Dining Experience.',
  logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=300&auto=format&fit=crop&q=80',
  bannerUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1600&auto=format&fit=crop&q=80',
  phone: '+1 (555) 345-6789',
  email: 'contact@bellavistapizzeria.com',
  address: '742 Evergreen Terrace, Downtown Gourmet Plaza, San Francisco, CA 94103',
  currency: 'USD',
  currencySymbol: '$',
  taxRatePercent: 8.5,
  enableDelivery: true,
  enablePickup: true,
  enableDineIn: true,
  autoAcceptOrders: false,
  estimatedPrepTime: 25,
  isActive: true,
  categories: [
    {
      id: 'cat-1-pizzas',
      name: 'Artisan Wood-Fired Pizzas',
      description: 'Slow-fermented 48-hour sourdough dough, hand-stretched and fired in our 900°F Marra Forni volcanic stone oven.',
      imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
      displayOrder: 1,
      isActive: true,
      items: [
        {
          id: 'item-pizza-1',
          name: 'Margherita D.O.P. Classica',
          description: 'San Marzano tomatoes, Campania buffalo mozzarella, fresh sweet basil, fleur de sel, cold-pressed olive oil.',
          imageUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=600&auto=format&fit=crop&q=80',
          basePrice: 16.99,
          dietaryTags: ['Vegetarian', 'Popular'],
          isFeatured: true,
          isAvailable: true,
          optionGroups: [
            {
              id: 'og-size',
              name: 'Select Pizza Size',
              minSelections: 1,
              maxSelections: 1,
              items: [
                { id: 'opt-size-m', name: 'Medium 12" (6 Slices)', price: 0.0, isDefault: true },
                { id: 'opt-size-l', name: 'Large 14" (8 Slices)', price: 4.5, isDefault: false },
                { id: 'opt-size-f', name: 'Family Grand 18" (12 Slices)', price: 9.5, isDefault: false },
              ],
            },
            {
              id: 'og-crust',
              name: 'Crust Choice',
              minSelections: 1,
              maxSelections: 1,
              items: [
                { id: 'opt-crust-neo', name: 'Traditional Neapolitan Stone Crust', price: 0.0, isDefault: true },
                { id: 'opt-crust-thin', name: 'Thin & Crispy Roman Style', price: 0.0, isDefault: false },
                { id: 'opt-crust-stuffed', name: 'Stuffed Garlic & Mozzarella Crust', price: 3.0, isDefault: false },
                { id: 'opt-crust-gf', name: 'Gluten-Free Cauliflower Crust', price: 4.0, isDefault: false },
              ],
            },
            {
              id: 'og-toppings',
              name: 'Extra Gourmet Toppings',
              minSelections: 0,
              maxSelections: 5,
              items: [
                { id: 'opt-top-buff', name: 'Extra Buffalo Mozzarella D.O.P', price: 2.5 },
                { id: 'opt-top-pep', name: 'Artisan Spicy Pepperoni', price: 2.75 },
                { id: 'opt-top-prosc', name: 'Prosciutto di Parma Riserva', price: 3.5 },
                { id: 'opt-top-mush', name: 'Wild Truffle Cremini Mushrooms', price: 2.25 },
                { id: 'opt-top-chili', name: 'Spicy Calabrian Chili Crunch', price: 1.25 },
              ],
            },
          ],
        },
        {
          id: 'item-pizza-2',
          name: 'Diavola Piccante & Hot Honey',
          description: 'Spicy Calabrian salami, smoked provolone, roasted red chili peppers, fresh oregano, hot infused chili blossom honey.',
          imageUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&auto=format&fit=crop&q=80',
          basePrice: 19.5,
          dietaryTags: ['Spicy', 'Chef Special'],
          isFeatured: true,
          isAvailable: true,
          optionGroups: [
            {
              id: 'og-size',
              name: 'Select Pizza Size',
              minSelections: 1,
              maxSelections: 1,
              items: [
                { id: 'opt-size-m', name: 'Medium 12" (6 Slices)', price: 0.0, isDefault: true },
                { id: 'opt-size-l', name: 'Large 14" (8 Slices)', price: 4.5, isDefault: false },
                { id: 'opt-size-f', name: 'Family Grand 18" (12 Slices)', price: 9.5, isDefault: false },
              ],
            },
            {
              id: 'og-toppings',
              name: 'Extra Gourmet Toppings',
              minSelections: 0,
              maxSelections: 5,
              items: [
                { id: 'opt-top-buff', name: 'Extra Buffalo Mozzarella D.O.P', price: 2.5 },
                { id: 'opt-top-pep', name: 'Artisan Spicy Pepperoni', price: 2.75 },
                { id: 'opt-top-chili', name: 'Spicy Calabrian Chili Crunch', price: 1.25 },
              ],
            },
          ],
        },
        {
          id: 'item-pizza-3',
          name: 'Black Truffle & Wild Forest Mushroom',
          description: 'White garlic truffle cream base, fontina cheese, sautéed cremini & shiitake mushrooms, thyme, white truffle oil.',
          imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
          basePrice: 21.0,
          dietaryTags: ['Vegetarian', 'Gourmet'],
          isFeatured: true,
          isAvailable: true,
          optionGroups: [
            {
              id: 'og-size',
              name: 'Select Pizza Size',
              minSelections: 1,
              maxSelections: 1,
              items: [
                { id: 'opt-size-m', name: 'Medium 12"', price: 0.0, isDefault: true },
                { id: 'opt-size-l', name: 'Large 14"', price: 4.5, isDefault: false },
              ],
            },
          ],
        },
        {
          id: 'item-pizza-4',
          name: 'Prosciutto San Daniele & Arugula',
          description: 'Crispy mozzarella base topped fresh out of the oven with 24-month aged Prosciutto, organic baby wild arugula, shaved parmigiano reggiano.',
          imageUrl: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
          basePrice: 22.5,
          dietaryTags: ['Premium'],
          isFeatured: false,
          isAvailable: true,
          optionGroups: [],
        },
      ],
    },
    {
      id: 'cat-2-burgers',
      name: 'Gourmet Smashed Burgers & Sandwiches',
      description: 'Double-seared custom blend Certified Angus Beef on toasted golden brioche buns, served with homemade signature dipping sauces.',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
      displayOrder: 2,
      isActive: true,
      items: [
        {
          id: 'item-burger-1',
          name: 'The Bella Vista Truffle Smokehouse Smash',
          description: 'Double smashed Angus patties, crispy onion strings, smoked gouda, truffle garlic aioli, butter brioche bun.',
          imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
          basePrice: 17.5,
          dietaryTags: ['Bestseller', 'Halal'],
          isFeatured: true,
          isAvailable: true,
          optionGroups: [
            {
              id: 'og-doneness',
              name: 'Meat Doneness & Temperature',
              minSelections: 1,
              maxSelections: 1,
              items: [
                { id: 'opt-done-m', name: 'Medium Pink (Juicy)', price: 0.0, isDefault: true },
                { id: 'opt-done-mw', name: 'Medium Well', price: 0.0, isDefault: false },
                { id: 'opt-done-wd', name: 'Well Done (Charred)', price: 0.0, isDefault: false },
              ],
            },
            {
              id: 'og-burger-boost',
              name: 'Burger Boosters & Sides',
              minSelections: 0,
              maxSelections: 3,
              items: [
                { id: 'opt-bacon', name: 'Thick Applewood Smoked Bacon', price: 2.5 },
                { id: 'opt-cheese', name: 'Aged White Truffle Cheddar', price: 1.75 },
                { id: 'opt-egg', name: 'Crispy Fried Egg', price: 1.5 },
              ],
            },
          ],
        },
        {
          id: 'item-burger-2',
          name: 'Crispy Nashville Hot Honey Chicken Crunch',
          description: 'Buttermilk 24h marinated chicken thigh, spicy cayenne honey glaze, house dill pickles, cool garlic slaw.',
          imageUrl: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600&auto=format&fit=crop&q=80',
          basePrice: 16.25,
          dietaryTags: ['Spicy', 'Popular'],
          isFeatured: true,
          isAvailable: true,
          optionGroups: [],
        },
        {
          id: 'item-burger-3',
          name: 'Beyond Truffle Herb Plant Burger',
          description: 'Plant-based 100% vegan patty, dairy-free smoked provolone, avocado smash, arugula, tomato on potato bun.',
          imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
          basePrice: 16.99,
          dietaryTags: ['Vegan', 'Vegetarian'],
          isFeatured: false,
          isAvailable: true,
          optionGroups: [],
        },
      ],
    },
    {
      id: 'cat-3-pastas',
      name: 'Fresh Handmade Pasta Fresca',
      description: 'Extruded daily using 100% Italian semolina rimacinata and organic pasture-raised egg yolks.',
      imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80',
      displayOrder: 3,
      isActive: true,
      items: [
        {
          id: 'item-pasta-1',
          name: 'Rigatoni Bolognese Tradizionale',
          description: 'Slow-braised 8-hour beef & veal ragù, San Marzano tomatoes, fresh rosemary, aged 24-month Parmigiano Reggiano.',
          imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?w=600&auto=format&fit=crop&q=80',
          basePrice: 19.75,
          dietaryTags: ['Popular', 'Chef Special'],
          isFeatured: true,
          isAvailable: true,
          optionGroups: [],
        },
        {
          id: 'item-pasta-2',
          name: 'Truffle & Porcini Wild Ravioli',
          description: 'Stuffed with ricotta and black summer truffles, tossed in creamy sage brown butter sauce with toasted hazelnuts.',
          imageUrl: 'https://images.unsplash.com/photo-1587740908075-9e245070dfaa?w=600&auto=format&fit=crop&q=80',
          basePrice: 22.0,
          dietaryTags: ['Vegetarian', 'Gourmet'],
          isFeatured: false,
          isAvailable: true,
          optionGroups: [],
        },
      ],
    },
    {
      id: 'cat-4-sides',
      name: 'Antipasti & Crispy Sides',
      description: 'Irresistible bites to start your feast or accompany your mains.',
      imageUrl: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=600&auto=format&fit=crop&q=80',
      displayOrder: 4,
      isActive: true,
      items: [
        {
          id: 'item-side-1',
          name: 'Truffle Parmesan Hand-Cut Fries',
          description: 'Double-fried Idaho potatoes tossed in white truffle essence, sea salt flakes, and aged parmesan with herb aioli dip.',
          imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
          basePrice: 8.5,
          dietaryTags: ['Vegetarian', 'Popular'],
          isFeatured: true,
          isAvailable: true,
          optionGroups: [],
        },
        {
          id: 'item-side-2',
          name: 'Crispy Calamari Fritti & Lemon Aioli',
          description: 'Flash-fried tender Rhode Island calamari rings, charred lemon cheek, homemade smoked paprika aioli.',
          imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80',
          basePrice: 13.5,
          dietaryTags: ['Seafood'],
          isFeatured: false,
          isAvailable: true,
          optionGroups: [],
        },
      ],
    },
    {
      id: 'cat-5-dolci',
      name: 'Dolci & Handcrafted Beverages',
      description: 'Sweet finishes and refreshing sparkling Italian sodas.',
      imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
      displayOrder: 5,
      isActive: true,
      items: [
        {
          id: 'item-dolci-1',
          name: 'Classic Venetian Tiramisù al Mascarpone',
          description: 'Savoiardi ladyfingers soaked in espresso & Marsala wine, layered with velvety whipped mascarpone cream and Valrhona cocoa.',
          imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&auto=format&fit=crop&q=80',
          basePrice: 9.5,
          dietaryTags: ['Vegetarian', 'Bestseller'],
          isFeatured: true,
          isAvailable: true,
          optionGroups: [],
        },
        {
          id: 'item-drink-1',
          name: 'San Pellegrino Sparkling Limonata (330ml)',
          description: 'Craft sparkling Sicilian lemon soda.',
          imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
          basePrice: 3.75,
          dietaryTags: ['Refreshing'],
          isFeatured: false,
          isAvailable: true,
          optionGroups: [],
        },
      ],
    },
  ],
  deliveryZones: [
    {
      id: 'zone-1',
      name: 'Zone 1: Downtown & Financial District (0-3 km)',
      zoneType: 'RADIUS',
      radiusKm: 3.0,
      minOrderAmount: 15.0,
      deliveryFee: 2.99,
      freeDeliveryThreshold: 40.0,
      estimatedTimeMin: 25,
      isActive: true,
    },
    {
      id: 'zone-2',
      name: 'Zone 2: Midtown & Waterfront (3-7 km)',
      zoneType: 'RADIUS',
      radiusKm: 7.0,
      minOrderAmount: 25.0,
      deliveryFee: 4.99,
      freeDeliveryThreshold: 55.0,
      estimatedTimeMin: 40,
      isActive: true,
    },
    {
      id: 'zone-3',
      name: 'Zone 3: Outer Suburbs & Heights (7-12 km)',
      zoneType: 'RADIUS',
      radiusKm: 12.0,
      minOrderAmount: 35.0,
      deliveryFee: 7.99,
      freeDeliveryThreshold: 80.0,
      estimatedTimeMin: 55,
      isActive: true,
    },
  ],
};

// Mock Initial Orders
export const initialOrders = [
  {
    id: 'ord-80124',
    orderNumber: '#BV-80124',
    restaurantId: 'resto-bella-vista-001',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.j@example.com',
    customerPhone: '+1 (555) 789-0123',
    orderType: 'DELIVERY',
    status: 'PENDING',
    deliveryAddress: '450 Mission Street, Apt 14B, San Francisco, CA 94105',
    deliveryZoneName: 'Zone 1: Downtown (0-3 km)',
    specialNotes: 'Please ring bell 14B. Extra napkins appreciated!',
    subtotal: 38.48,
    taxAmount: 3.27,
    deliveryFee: 2.99,
    discountAmount: 0.0,
    totalAmount: 44.74,
    paymentMethod: 'CASH_ON_DELIVERY',
    paymentStatus: 'UNPAID',
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'oi-1',
        itemName: 'Margherita D.O.P. Classica',
        itemPrice: 16.99,
        quantity: 1,
        itemTotal: 21.49,
        selectedOptions: [
          { groupName: 'Select Pizza Size', optionName: 'Large 14" (8 Slices)', optionPrice: 4.5 },
          { groupName: 'Crust Choice', optionName: 'Traditional Neapolitan Stone Crust', optionPrice: 0.0 },
        ],
      },
      {
        id: 'oi-2',
        itemName: 'The Bella Vista Truffle Smokehouse Smash',
        itemPrice: 17.5,
        quantity: 1,
        itemTotal: 17.5,
        selectedOptions: [
          { groupName: 'Meat Doneness', optionName: 'Medium Pink', optionPrice: 0.0 },
        ],
      },
    ],
  },
  {
    id: 'ord-80120',
    orderNumber: '#BV-80120',
    restaurantId: 'resto-bella-vista-001',
    customerName: 'David Miller',
    customerEmail: 'david.m@example.com',
    customerPhone: '+1 (555) 432-8765',
    orderType: 'PICKUP',
    status: 'ACCEPTED',
    acceptedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    estimatedReadyAt: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
    specialNotes: 'No cutlery needed.',
    subtotal: 28.25,
    taxAmount: 2.4,
    deliveryFee: 0.0,
    discountAmount: 0.0,
    totalAmount: 30.65,
    paymentMethod: 'CARD_ONLINE',
    paymentStatus: 'PAID',
    createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'oi-3',
        itemName: 'Rigatoni Bolognese Tradizionale',
        itemPrice: 19.75,
        quantity: 1,
        itemTotal: 19.75,
        selectedOptions: [],
      },
      {
        id: 'oi-4',
        itemName: 'Truffle Parmesan Hand-Cut Fries',
        itemPrice: 8.5,
        quantity: 1,
        itemTotal: 8.5,
        selectedOptions: [],
      },
    ],
  },
  {
    id: 'ord-80115',
    orderNumber: '#BV-80115',
    restaurantId: 'resto-bella-vista-001',
    customerName: 'Elena Rostova',
    customerEmail: 'elena.r@example.com',
    customerPhone: '+1 (555) 901-2345',
    orderType: 'DELIVERY',
    status: 'COMPLETED',
    deliveryAddress: '220 Montgomery St, San Francisco, CA',
    deliveryZoneName: 'Zone 1: Downtown (0-3 km)',
    subtotal: 44.5,
    taxAmount: 3.78,
    deliveryFee: 2.99,
    discountAmount: 0.0,
    totalAmount: 51.27,
    paymentMethod: 'CARD_ONLINE',
    paymentStatus: 'PAID',
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'oi-5',
        itemName: 'Diavola Piccante & Hot Honey',
        itemPrice: 19.5,
        quantity: 2,
        itemTotal: 39.0,
        selectedOptions: [],
      },
      {
        id: 'oi-6',
        itemName: 'San Pellegrino Sparkling Limonata (330ml)',
        itemPrice: 3.75,
        quantity: 2,
        itemTotal: 7.5,
        selectedOptions: [],
      },
    ],
  },
];
