const categories = [
  { id: 1, name: "Desktops", icon: "HardDrive", slug: "desktops", image: "/desktop.webp" },
  { id: 2, name: "Laptops", icon: "Laptop", slug: "laptop-notebook", image: "/laptop.webp" },
  { id: 3, name: "Components", icon: "Cpu", slug: "component", image: "/components.jpg" },
  { id: 4, name: "Monitors", icon: "Monitor", slug: "monitor", image: "/monitor.webp" },
  { id: 5, name: "Phones", icon: "Smartphone", slug: "mobile-phone", image: "/phone.webp" },
  { id: 6, name: "Tablets", icon: "Tablet", slug: "tablet-pc", image: "/tab.webp" },
  { id: 7, name: "Cameras", icon: "Camera", slug: "camera", image: "/camera.jpg" },
  { id: 8, name: "Security", icon: "Shield", slug: "security-camera", image: "/security.webp" }
];

const products = [
  {
    id: 1,
    name: "Quantum X Gaming Laptop",
    slug: "quantum-x-gaming-laptop",
    price: 2499,
    category: "laptop-notebook",
    image: "/laptop.webp",
    images: ["/laptop.webp", "/laptop.webp", "/laptop.webp"],
    specs: ["Intel i9-14900H", "RTX 4090", "32GB DDR5", "1TB NVMe SSD"],
    description: "High-performance gaming laptop with latest Intel processor and RTX 4090 graphics.",
    featured: true,
    brand: "Quantum",
    model: "QX-14900K",
    stock: true,
  },
  {
    id: 2,
    name: "Nebula Pro Ultrabook",
    slug: "nebula-pro-ultrabook",
    price: 1899,
    category: "laptop-notebook",
    image: "/laptop.webp",
    images: ["/laptop.webp", "/laptop.webp"],
    specs: ["Intel i7-13700H", "RTX 4060", "16GB DDR5", "512GB SSD"],
    description: "Sleek and powerful ultrabook for professionals.",
    featured: true,
    brand: "Nebula",
    model: "NP-13700H",
    stock: true,
  },
  {
    id: 3,
    name: "ROG Strix G16",
    slug: "rog-strix-g16",
    price: 3299,
    category: "laptop-notebook",
    image: "/laptop.webp",
    images: ["/laptop.webp"],
    specs: ["AMD Ryzen 9 7940HS", "RTX 4080", "64GB DDR5", "2TB SSD"],
    description: "Ultimate gaming machine with Ryzen 9 and RTX 4080.",
    featured: true,
    brand: "ASUS",
    model: "G16-7940HS",
    stock: true,
  },
  {
    id: 4,
    name: "MacBook Pro M3 Max",
    slug: "macbook-pro-m3-max",
    price: 3999,
    category: "laptop-notebook",
    image: "/laptop.webp",
    images: ["/laptop.webp"],
    specs: ["Apple M3 Max", "48GB Unified", "1TB SSD", "14-core GPU"],
    description: "Apple's most powerful laptop with M3 Max chip.",
    featured: false,
    brand: "Apple",
    model: "MBP-M3-Max",
    stock: true,
  },
  {
    id: 5,
    name: "Nebula Pro Phone 15",
    slug: "nebula-pro-phone-15",
    price: 1299,
    category: "mobile-phone",
    image: "/phone.webp",
    images: ["/phone.webp"],
    specs: ["Snapdragon 8 Gen 3", "12GB RAM", "256GB Storage", "200MP Camera"],
    description: "Flagship phone with cutting-edge camera system.",
    featured: true,
    brand: "Nebula",
    model: "NP-15-Pro",
    stock: true,
  },
  {
    id: 6,
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    price: 1599,
    category: "mobile-phone",
    image: "/phone.webp",
    images: ["/phone.webp"],
    specs: ["A18 Pro Chip", "8GB RAM", "512GB Storage", "48MP Camera"],
    description: "Apple's latest iPhone with A18 Pro processor.",
    featured: true,
    brand: "Apple",
    model: "IP-16-Pro-Max",
    stock: true,
  },
  {
    id: 7,
    name: "Galaxy S26 Ultra",
    slug: "galaxy-s26-ultra",
    price: 1399,
    category: "mobile-phone",
    image: "/phone.webp",
    images: ["/phone.webp"],
    specs: ["Exynos 2400", "12GB RAM", "512GB Storage", "200MP Camera"],
    description: "Samsung's premium flagship with S Pen support.",
    featured: false,
    brand: "Samsung",
    model: "GS-S26-Ultra",
    stock: false,
  },
  {
    id: 8,
    name: "Quantum X Desktop PC",
    slug: "quantum-x-desktop-pc",
    price: 3499,
    category: "desktops",
    image: "/desktop.webp",
    images: ["/desktop.webp", "/desktop.webp"],
    specs: ["Intel i9-14900K", "RTX 4090", "64GB DDR5", "4TB NVMe SSD"],
    description: "Ultimate gaming and workstation desktop with top-tier specs.",
    featured: true,
    brand: "Quantum",
    model: "QX-Desktop-14900K",
    stock: true,
  },
  {
    id: 11,
    name: "Intel Core i9-14900K",
    slug: "intel-core-i9-14900k",
    price: 599,
    category: "component",
    image: "/components.jpg",
    images: ["/components.jpg"],
    specs: ["24 Cores", "32 Threads", "6.0GHz Boost", "LGA1700"],
    description: "Intel's flagship desktop processor with 24 cores.",
    featured: false,
    brand: "Intel",
    model: "i9-14900K",
    stock: true,
  },
  {
    id: 14,
    name: '27" 4K Gaming Monitor',
    slug: '27-inch-4k-gaming-monitor',
    price: 699,
    category: "monitor",
    image: "/monitor.webp",
    images: ["/monitor.webp"],
    specs: ['27-inch', '4K UHD', '144Hz', '1ms Response'],
    description: "Professional 4K monitor for gaming and content creation.",
    featured: true,
    brand: "Samsung",
    model: "S27-4K-Gaming",
    stock: true,
  }
];

module.exports = { categories, products };
